CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) UNIQUE NOT NULL,
    description varchar(500)
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description varchar(500),
    price DECIMAL,
    category_id BIGINT,
    image_url TEXT,
    active BOOLEAN,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);