grpc.server.port=59091

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-serializer=ru.practicum.telemetry.TelemetryAvroSerializer
spring.kafka.producer.client_id_config=collector-producer
telemetry.topic.hubs=telemetry.hubs.v1
telemetry.topic.sensors=telemetry.sensors.v1