CREATE TABLE IF NOT EXISTS inventory_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    quantity INTEGER,
    reserved_quantity INTEGER,
    available_quantity INTEGER,
    version BIGINT DEFAULT 0
);