grpc:
  server:
    port: 59091

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: ru.practicum.telemetry.TelemetryAvroSerializer
      client_id_config: collector-producer
telemetry:
  topic:
    hubs: telemetry.hubs.v1
    sensors: telemetry.sensors.v1