CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name varchar(50),
    customer_email varchar(50),
    status varchar(20),
    total_price DECIMAL,
    status_details varchar(20),
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT,
    product_name varchar(255),
    quantity INTEGER,
    price DECIMAL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);