grpc.server.port=59091

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.value-serializer=ru.practicum.telemetry.TelemetryAvroSerializer
spring.kafka.producer.config=aggregator-producer
spring.kafka.consumer.config=aggregator-consumer
spring.kafka.group.config=aggregator.group
telemetry.topic.hubs=telemetry.hubs.v1
telemetry.topic.sensors=telemetry.sensors.v1
telemetry.topic.snapshots=telemetry.snapshots.v1