spring:
  main:
    banner-mode: OFF
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: dbuser
    password: 12345
  kafka:
    consumer:
      common:
        bootstrap-servers: localhost:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        enable-auto-commit: false
      snapshot:
        value-deserializer: ru.practicum.telemetry.SensorsSnapshotDeserializer
        client-id: analyzer-snapshot-consumer
        group-id: analyzer.snapshot.group
        auto-offset-reset: latest
        max-poll-records: 5
        max-poll-interval: 60000
      hub:
        value-deserializer: ru.practicum.telemetry.HubEventDeserializer
        client-id: analyzer-hub-consumer
        group-id: analyzer.hub.group
        auto-offset-reset: earliest
        max-poll-records: 50
        max-poll-interval: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.practicum.telemetry: DEBUG

telemetry:
  topic:
    hubs: 'telemetry.hubs.v1'
    sensors: 'telemetry.sensors.v1'
    snapshots: 'telemetry.snapshots.v1'